# Generated by Django 3.1.7 on 2021-03-09 17:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_technologyforwebdevelopment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdivision',
            name='page',
        ),
        migrations.AddField(
            model_name='workpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(default='', form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(default=''))], default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TechnologyForWebDevelopment',
        ),
        migrations.DeleteModel(
            name='WorkDivision',
        ),
    ]
