# Generated by Django 3.1.7 on 2021-03-09 18:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210309_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading_and_paragraph', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='', help_text='Add your title')), ('paragraph', wagtail.core.blocks.RichTextBlock(default='', help_text='Add your content'))]))]),
        ),
        migrations.CreateModel(
            name='TechnologyOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('technology_title', models.CharField(max_length=255)),
                ('technology_description', wagtail.core.fields.RichTextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpage', to='work.workpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
