# Generated by Django 3.1.7 on 2021-03-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20210311_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullstackpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='technologypage',
            name='description',
        ),
    ]
