# Generated by Django 3.1.7 on 2021-03-11 10:09

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20210311_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullstackpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='technologypage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
