# Generated by Django 3.1.7 on 2021-03-11 10:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20210311_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologypage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='technologypage',
            name='technology_title',
        ),
        migrations.CreateModel(
            name='TechnologyDetailOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologypage', to='work.technologypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
