# Generated by Django 3.1.7 on 2021-03-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20210311_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologydetailorderable',
            old_name='title',
            new_name='software_title',
        ),
    ]
