# Generated by Django 3.1.7 on 2021-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210308_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeselectionorderable',
            name='content',
        ),
        migrations.AddField(
            model_name='homeselectionorderable',
            name='selection_handle',
            field=models.CharField(default='home', max_length=255),
        ),
        migrations.AddField(
            model_name='homeselectionorderable',
            name='selection_title',
            field=models.CharField(default='Home', max_length=255),
        ),
        migrations.DeleteModel(
            name='HomeSelection',
        ),
    ]
