# Generated by Django 3.1.7 on 2021-03-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210308_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeselectionorderable',
            name='selection_handle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homeselectionorderable',
            name='selection_title',
            field=models.CharField(max_length=255),
        ),
    ]
