# Generated by Django 3.1.7 on 2021-03-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_aboutindexpage_about_index_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_title',
        ),
    ]
