# Generated by Django 3.1.7 on 2021-03-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_aboutpage_about_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='body',
            new_name='content',
        ),
    ]
