# Generated by Django 3.1.7 on 2021-03-07 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0004_auto_20210307_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPage',
            new_name='AbouttPage',
        ),
    ]
