# Generated by Django 3.1.7 on 2021-03-07 14:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('about', '0005_auto_20210307_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbouttPage',
            new_name='AboutPage',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='content',
            new_name='body',
        ),
    ]
