# Generated by Django 3.1.7 on 2021-03-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('about', '0006_auto_20210307_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='side_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
