# Generated by Django 3.1.7 on 2021-03-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('about', '0009_auto_20210308_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutIndexPage',
        ),
    ]
